# Generated by Django 5.1 on 2024-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="title of the post",
                        max_length=100,
                        verbose_name="Blog entry title",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="has title in it",
                        max_length=100,
                        verbose_name="readable url",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="write your text here",
                        null=True,
                        verbose_name="blog post text",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Upload preview photo",
                        null=True,
                        upload_to="blog/preview",
                        verbose_name="blog post preview",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="date of post creation",
                        null=True,
                        verbose_name="creation date",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of views",
                        verbose_name="visits counter",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
            ],
        ),
    ]
