# Generated by Django 5.1 on 2024-09-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog_entry",
            options={
                "ordering": ("creation_date",),
                "verbose_name": "blog_entry",
                "verbose_name_plural": "blog_entries",
            },
        ),
    ]
