# Generated by Django 5.1 on 2024-09-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_entry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_entry",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="has title in it",
                max_length=100,
                null=True,
                verbose_name="readable url",
            ),
        ),
    ]
