  # Generated by Django 5.1 on 2024-09-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='describe the product', null=True, verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="Product's name", max_length=100, verbose_name='название продукта'),
        ),
    ]
