# Generated by Django 5.1 on 2024-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of views", verbose_name="visits counter"
            ),
        ),
    ]
