# Generated by Django 5.1 on 2024-10-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_views_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="product version number",
                        max_length=50,
                        verbose_name="Version number",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="product version name",
                        max_length=50,
                        verbose_name="Version name",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="current_version"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Version",
                    ),
                ),
            ],
        ),
    ]
